# Generated by Django 3.0.5 on 2020-04-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbook', '0002_auto_20200408_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tex',
            new_name='text',
        ),
    ]
